import {useQuery, useMutation} from "@tanstack/react-query"
import { useDispatch } from "react-redux"
import type { AppDispatch } from "../store"
import { fetchBook,createBook,updateBook,deleteBook,fetchMembar,createMembar,updateMember,deleteMember,fetchIssuedBooks,createIssue,updateIssue } from "../services/libraryApi"
import { addBook,updateBooks,deleteBooks,addMember,updateMembers,deleteMembers,issueBook,returnBook } from "../store/library.slice"